//! Stable field IDs for MessagePack payloads. Never reassign existing IDs.
macro_rules! fields {
    ($($id:literal => $name:literal,)*) => {
        #[cfg(test)]
        pub(super) const FIELDS: &[&str] = &[$($name,)*];
        pub(super) fn field_id(name: &str) -> Option<u64> { match name { $($name => Some($id),)* _ => None } }
        pub(super) fn field_name(id: u64) -> Option<&'static str> { match id { $($id => Some($name),)* _ => None } }
    };
}
fields! {
    0 => "type",
    1 => "id",
    2 => "method",
    3 => "params",
    4 => "result",
    5 => "error",
    6 => "code",
    7 => "message",
    8 => "retry",
    9 => "repoId",
    10 => "snapshot",
    11 => "entries",
    12 => "nextCursor",
    13 => "path",
    14 => "bytesB64",
    15 => "display",
    16 => "kind",
    17 => "operationId",
    18 => "expectedSnapshot",
    19 => "streamId",
    20 => "seq",
    21 => "contentBytesB64",
    22 => "action",
    23 => "actions",
    24 => "additions",
    25 => "ahead",
    26 => "algorithm",
    27 => "amended",
    28 => "annotated",
    29 => "annotation",
    30 => "applied",
    31 => "atSnapshot",
    32 => "authentication",
    33 => "author",
    34 => "backend",
    35 => "bare",
    36 => "base",
    37 => "basis",
    38 => "behind",
    39 => "binary",
    40 => "branch",
    41 => "branchKind",
    42 => "byteOffset",
    43 => "bytes",
    44 => "canAbort",
    45 => "canContinue",
    46 => "canSkip",
    47 => "capabilities",
    48 => "clientId",
    49 => "clientVersion",
    50 => "clone",
    51 => "cloned",
    52 => "closed",
    53 => "command",
    54 => "commandLogs",
    55 => "commitOid",
    56 => "committer",
    57 => "commonRepoId",
    58 => "configuration",
    59 => "conflict",
    60 => "conflicted",
    61 => "content",
    62 => "contextLines",
    63 => "current",
    64 => "cursor",
    65 => "deletions",
    66 => "destinationBranch",
    67 => "detached",
    68 => "detailsOmitted",
    69 => "dropped",
    70 => "durationMs",
    71 => "editable",
    72 => "email",
    73 => "engine",
    74 => "entry",
    75 => "entryId",
    76 => "entryIds",
    77 => "exitCode",
    78 => "expectedOid",
    79 => "expectedRemoteOid",
    80 => "expectedToken",
    81 => "features",
    82 => "fetch",
    83 => "fileIndex",
    84 => "files",
    85 => "filter",
    86 => "flags",
    87 => "forPush",
    88 => "force",
    89 => "format",
    90 => "gitDir",
    91 => "group",
    92 => "groupCounts",
    93 => "hasOmissions",
    94 => "head",
    95 => "hex",
    96 => "https",
    97 => "hunks",
    98 => "ids",
    99 => "includeDepth",
    100 => "includeUntracked",
    101 => "index",
    102 => "initialBranch",
    103 => "initialized",
    104 => "instanceId",
    105 => "integration",
    106 => "interrupted",
    107 => "keepIndex",
    108 => "lastSeq",
    109 => "level",
    110 => "limits",
    111 => "lineComplete",
    112 => "lineEncoding",
    113 => "lineIndex",
    114 => "lines",
    115 => "listToken",
    116 => "lockReason",
    117 => "locked",
    118 => "main",
    119 => "mainline",
    120 => "managed",
    121 => "matchedEntries",
    122 => "matchingEntries",
    123 => "maxBytes",
    124 => "maxChunkBytes",
    125 => "maxFrameBytes",
    126 => "maxInflight",
    127 => "maxPageItems",
    128 => "messageBytes",
    129 => "messageTruncated",
    130 => "metadata",
    131 => "methods",
    132 => "mode",
    133 => "name",
    134 => "needsResolution",
    135 => "newBranch",
    136 => "newLine",
    137 => "newLines",
    138 => "newMode",
    139 => "newName",
    140 => "newOid",
    141 => "newPath",
    142 => "newStart",
    143 => "nonce",
    144 => "objectFormat",
    145 => "objectFormats",
    146 => "objectType",
    147 => "offset",
    148 => "offsetMinutes",
    149 => "oid",
    150 => "oldLine",
    151 => "oldLines",
    152 => "oldMode",
    153 => "oldOid",
    154 => "oldPath",
    155 => "oldStart",
    156 => "omissionReason",
    157 => "ontoOid",
    158 => "openRequired",
    159 => "operationState",
    160 => "origin",
    161 => "ours",
    162 => "output",
    163 => "pageSize",
    164 => "parentIndex",
    165 => "parentOid",
    166 => "parents",
    167 => "peeledOid",
    168 => "peeledType",
    169 => "previousOid",
    170 => "protocol",
    171 => "prunable",
    172 => "prune",
    173 => "push",
    174 => "pushUrl",
    175 => "rawOid",
    176 => "readOnly",
    177 => "reason",
    178 => "reference",
    179 => "refreshRequired",
    180 => "reinstateIndex",
    181 => "remote",
    182 => "remoteBranch",
    183 => "remoteToken",
    184 => "replacedOid",
    185 => "repository",
    186 => "resolvedRevision",
    187 => "revision",
    188 => "root",
    189 => "saved",
    190 => "selectedPath",
    191 => "side",
    192 => "size",
    193 => "source",
    194 => "sourceSnapshot",
    195 => "ssh",
    196 => "staged",
    197 => "startOid",
    198 => "state",
    199 => "status",
    200 => "streamWindow",
    201 => "symbolicTarget",
    202 => "tagger",
    203 => "target",
    204 => "targetOid",
    205 => "text",
    206 => "theirs",
    207 => "time",
    208 => "token",
    209 => "totalEntries",
    210 => "totalFiles",
    211 => "totalLines",
    212 => "totalUnits",
    213 => "tracking",
    214 => "truncated",
    215 => "tuple_v1",
    216 => "unborn",
    217 => "unstaged",
    218 => "untracked",
    219 => "upstream",
    220 => "upstreamOid",
    221 => "upstreamRef",
    222 => "url",
    223 => "value",
    224 => "version",
    225 => "versions",
    226 => "workingTree",
    227 => "worktree",
    228 => "diff",
    229 => "merge",
    230 => "payloadHash",
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn existing_field_ids_are_frozen_and_unique() {
        let mut hash = 0xcbf29ce484222325u64;
        for (id, name) in FIELDS.iter().enumerate() {
            assert_eq!(field_id(name), Some(id as u64));
            assert_eq!(field_name(id as u64), Some(*name));
        }
        // Append fields after this prefix; changing these IDs breaks deployed peers.
        for name in &FIELDS[..231] {
            for byte in name.bytes().chain(std::iter::once(0)) {
                hash = (hash ^ u64::from(byte)).wrapping_mul(0x100000001b3);
            }
        }
        assert_eq!(hash, 0x5106f81bf3976c1a);
    }
}
