import { decodeGitOperation } from "../domain/gitResponses";
import { readFileSync } from "node:fs";
import { expect, it, vi } from "vitest";
import type { GitRequest, GitWriteAction } from "../domain/git";
import { GitRepositoryClient } from "./gitRepository";

// Generated by disposable SSH or CLI fixtures. Ordinary unit runs need neither.
const tracePath = process.env.NEWPORT_GIT_TRACE_PATH;
it.skipIf(!tracePath)(
  "decodes the real Git workflow through every typed Git client method",
  async () => {
    const rows = readFileSync(tracePath!, "utf8")
      .trim()
      .split("\n")
      .map(
        (line) =>
          JSON.parse(line) as {
            request:
              | GitRequest
              | { method: "operation.review"; params: { operationId: string } };
            response?: unknown;
            error?: unknown;
          },
      );
    const covered = new Set<string>();
    const successfulActions = new Set<string>();
    const resolvingActions = new Set<string>();
    for (const row of rows) {
      if (!("response" in row)) continue;
      const session = {
        request: vi.fn().mockResolvedValue(row.response),
        forget: vi.fn().mockResolvedValue(undefined),
      };
      const client = new GitRepositoryClient(session);
      const r = row.request;
      try {
        switch (r.method) {
          case "repo.open":
            await client.open(r.params.path);
            break;
          case "repo.close":
            await client.close(r.params.repoId);
            break;
          case "repo.status_summary":
            await client.statusSummary(r.params.repoId ?? r.params.path!);
            break;
          case "repo.status":
            await client.status(r.params.repoId, r.params.cursor ?? undefined);
            break;
          case "repo.history":
            await client.history(
              r.params.repoId,
              r.params.revision,
              r.params.cursor ?? undefined,
            );
            break;
          case "repo.commit":
            await client.commit(r.params.repoId, r.params.commitOid);
            break;
          case "repo.branches":
            await client.branches(
              r.params.repoId,
              r.params.cursor ?? undefined,
              {
                filter: r.params.filter,
                branchKind: r.params.branchKind,
                pageSize: r.params.pageSize,
              },
            );
            break;
          case "repo.remote_names":
            await client.remoteNames(r.params);
            break;
          case "repo.remote":
            await client.remote(r.params.repoId, r.params.name);
            break;
          case "repo.remotes":
            await client.remotes(r.params.repoId);
            break;
          case "repo.remote_refs":
            await client.remoteRefs(r.params);
            break;
          case "repo.stashes":
            await client.stashes(r.params.repoId, r.params.cursor ?? undefined);
            break;
          case "repo.tag":
            await client.tag(r.params.repoId, r.params.oid);
            break;
          case "repo.tags":
            await client.tags(r.params.repoId, r.params.cursor ?? undefined);
            break;
          case "repo.worktrees":
            await client.worktrees(
              r.params.repoId,
              r.params.cursor ?? undefined,
            );
            break;
          case "repo.blob_page":
            await client.blobPage(r.params);
            break;
          case "repo.blob":
            await client.blob(r.params.repoId, r.params.oid);
            break;
          case "repo.diff_page":
            await client.diffPage(r.params);
            break;
          case "repo.diff":
            await client.diff(r.params);
            break;
          case "repo.commit_diff_page":
            await client.commitDiffPage(r.params);
            break;
          case "repo.commit_diff":
            await client.commitDiff(r.params);
            break;
          case "repo.commit_files":
            await client.commitFiles(r.params);
            break;
          case "operation.start": {
            const result = await client.start(r.params);
            if (result.state === "succeeded")
              successfulActions.add(r.params.action.kind);
            if (result.state === "needs_resolution")
              resolvingActions.add(r.params.action.kind);
            break;
          }
          case "operation.review":
            // Review is native-only; verify the shared response decoder without
            // adding a renderer RPC mutation entry point.
            decodeGitOperation(await session.request(r), r.params.operationId);
            break;
          case "operation.get":
            await client.operation(r.params.operationId);
            break;
          case "repo.init":
          case "repo.clone":
            await client.bootstrap(r);
            break;
          default: {
            const unreachable: never = r;
            throw new Error(
              `Unhandled request: ${JSON.stringify(unreachable)}`,
            );
          }
        }
        expect(
          session.forget,
          `${r.method} must decode without terminating the session`,
        ).not.toHaveBeenCalled();
        expect(session.request).toHaveBeenCalledOnce();
        covered.add(r.method);
      } catch (cause) {
        throw new Error(`Real Git response failed for ${r.method}`, { cause });
      }
    }
    // Exhaustive at compile time: a new action must acquire live coverage here.
    const expectedActions: Record<GitWriteAction["kind"], true> = {
      stage: true,
      unstage: true,
      discard: true,
      "conflict.resolve": true,
      reset: true,
      commit: true,
      "commit.amend": true,
      "branch.create": true,
      "branch.rename": true,
      "branch.delete": true,
      "branch.set_upstream": true,
      "branch.delete_remote": true,
      checkout: true,
      "remote.add": true,
      "remote.rename": true,
      "remote.set_url": true,
      "remote.remove": true,
      fetch: true,
      push: true,
      "push.with_lease": true,
      "pull.fast_forward": true,
      merge: true,
      "merge.fast_forward": true,
      "merge.abort": true,
      "integration.continue": true,
      "integration.abort": true,
      "integration.skip": true,
      cherry_pick: true,
      revert: true,
      rebase: true,
      "stash.save": true,
      "stash.apply": true,
      "stash.pop": true,
      "stash.drop": true,
      "tag.create": true,
      "tag.delete": true,
      "tag.push": true,
      "tag.delete_remote": true,
      "worktree.add": true,
      "worktree.remove": true,
      "worktree.prune": true,
      "worktree.repair": true,
      "worktree.lock": true,
      "worktree.unlock": true,
    };
    expect(
      [...new Set([...successfulActions, ...resolvingActions])].sort(),
    ).toEqual(Object.keys(expectedActions).sort());
    console.info(
      `Git write coverage: ${successfulActions.size} succeeded; conflict workflows: ${[...resolvingActions].sort().join(", ")}`,
    );
    expect([...covered].sort()).toEqual(
      [
        "repo.open",
        "repo.close",
        "repo.status",
        "repo.status_summary",
        "repo.history",
        "repo.commit",
        "repo.branches",
        "repo.remotes",
        "repo.remote",
        "repo.remote_names",
        "repo.remote_refs",
        "repo.stashes",
        "repo.tags",
        "repo.tag",
        "repo.worktrees",
        "repo.blob",
        "repo.blob_page",
        "repo.diff",
        "repo.diff_page",
        "repo.commit_diff",
        "repo.commit_diff_page",
        "repo.commit_files",
        "operation.start",
        "operation.get",
        "operation.review",
        "repo.init",
        "repo.clone",
      ].sort(),
    );
  },
);
